# Generated by Django 4.2.7 on 2023-11-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_change_24h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percent_change_1h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percent_change_7d', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percent_change_30d', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percent_change_60d', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percent_change_90d', models.DecimalField(decimal_places=2, max_digits=6)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('market_cap_dominance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fully_diluted_market_cap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
