# Generated by Django 4.1 on 2023-11-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cryptocurrency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='RecentWork',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
