# Generated by Django 4.1 on 2023-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_visit', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('found_needed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('reason', models.CharField(choices=[('social media', 'Social Media'), ('advertising', 'Advertising'), ('google search', 'Google Search'), ('friend', 'Friend')], max_length=15)),
                ('ease_of_use', models.CharField(choices=[('veryEasy', 'Very Easy'), ('easy', 'Easy'), ('average', 'Average'), ('difficult', 'Difficult'), ('veryDifficult', 'Very Difficult')], max_length=15)),
                ('likelihood_to_return', models.CharField(choices=[('extremelyLikely', 'Extremely Likely'), ('veryLikely', 'Very Likely'), ('moderatelyLikely', 'Moderately Likely'), ('slightlyLikely', 'Slightly Likely'), ('unlikelyToReturn', 'Unlikely to Return')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
