# Generated by Django 4.2.7 on 2023-11-27 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='price',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='transaction_date',
            new_name='transaction_time',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
