# Generated by Django 4.2.7 on 2023-11-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_orderhistory_user'),
        ('core', '0008_rename_price_orderhistory_total_and_more'),
    ]

    operations = [
    ]
